apiVersion: batch/v1
kind: Job
metadata:
  name: single-job
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: golang-app
        
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job
          image: Imagename
          
          env:
          - name: color
            value: blue
